cuando_entra: '&7[&a+&7] %luckperms_prefix%%player_name%'
cuando_sale: '&7[&c-&7] %luckperms_prefix%%player_name%'
cuando_entra_admin: '&8[&cAdmin&8] &c%player_name% &6ha entrado al servidor!'
titulo_entra: '&fBienvenido de nuevo! &e%nombre%'
subtitulo_entra: '&btienda.anycraft.net'
console_message: '&e[AnyMessages] &4Ha entrado un jugador con permisos &e[%nombre%]'
bed_respawn: '&eHas puesto tu punto de respawn'
mensaje_respawn: '&eHas respawneado ;)'
reload_msg: '&eLa configuración ha sido actualizada!'
toxic_msg: '&cNo seas toxico!'
no_perm_msg: '&fEste comando no existe'
console_reload_msg: '&e%player% ha actualizado la configuración'
palabra_no_esta: '&cEsta palabra no esta en la lista'
palabra_esta: '&cEsta palabra ya se encuentra en la lista'

luckperms_chat: false
prefix_chat: '%luckperms_prefix%'

mensaje_hacia_jugador:
- '&fBienvenido a &emc.anytown.net'
- '&fTienda:&b tienda.anytown.net'

mensajes_bloqueados:
- 'rata'
- 'puto'
- 'L'
- 'loser'
- 'l0ser'
- 'malo'
- 'mierda'
- 'gay'
- 'puta'
- 'pto'
- 'pt'
- 'puta'
- 'hdp'
- 'hp'
- 'hijo de puta'
- 'hijodeputa'
- 'fuck'
- 'fuck off'
- 'shit'
- 'holy fuck'
- 'shut up'
- 'nigga'
- 'nigger'
- 'n1ga'
- 'n1gger'
- 'n1gg3r'
- 'n1gg4'
